<?php

namespace App\Enums;

use BenSampo\Enum\Enum;

/**
 * @method static static OptionOne()
 * @method static static OptionTwo()
 * @method static static OptionThree()
 */
final class ApiEventEnum extends Enum
{
    const INITIATED_LOGIN = 'INITIATED_LOGIN';
    const INITIATED_LOGOUT = 'INITIATED_LOGOUT';
    const INITIATED_SIGNUP = 'INITIATED_SIGNUP';
    const UPDATED_USER_DETAILS = 'UPDATED_USER_DETAILS';
    const INITIATED_FUND_TRANSFER = 'INITIATED_FUND_TRANSFER';
    const ACCEPTED_FUNDREQUEST = 'ACCEPTED_FUNDREQUEST';
    const REJECTED_FUNDREQUEST = 'REJECTED_FUNDREQUEST';
    const INITIATED_BILL_PAYMENT = 'INITIATED_BILL_PAYMENT';
    const INITIATED_COMPLAINT = 'INITIATED_COMPLAINT';
    const UPDATED_USER_PERMISSION = 'UPDATED_USER_PERMISSION';
    const UPDATED_USER_IMAGES = 'UPDATED_USER_IMAGES';
    const WALLET_BALANCE_LOCKED_STATUS = 'WALLET_BALANCE_LOCKED_STATUS';
    const ACCOUNT_BLOCKED_STATUS = 'ACCOUNT_BLOCKED_STATUS';
    const PROCESS_BANK_WITHDRAWAL = 'PROCESS_BANK_WITHDRAWAL';
    const SENT_ALERT = 'SENT_ALERT';


}
