<?php

namespace App\Enums;

use BenSampo\Enum\Enum;


final class FundRequestType extends Enum
{
    const DIRECT = 'DIRECT';        #FOR PAYMENTS ESSENTIALLY MEANS FUND TRANSFER HAS HAPPENED DIRECTLY FROM SENDER->RECIPIENT
    const REQUEST = 'REQUEST';      #FOR SENDING A REQUEST TO SENDER AND THEN SENDER ACCEPTING IT
    const AGENT_WALLET_REFILL = 'AGENT_WALLET_REFILL'; #FOR CASES WHERE CUSTOMER/MERCHANT HAS AGENT WALLET AND NEEDS FUNDS ON AGENT WALLET
}
