<?php

namespace App\Enums;

use BenSampo\Enum\Enum;


final class WalletTransactionType extends Enum
{
    const WALLET_TRANSFER = 'WALLET_TRANSFER';
    const RECHARGE = 'RECHARGE';
    const DEPOSIT = 'DEPOSIT';
    const DEPOSIT_COMMISSION = 'DEPOSIT_COMMISSION';
    const WITHDRAWAL = 'WITHDRAWAL';
    const WITHDRAWAL_CHARGE = 'WITHDRAWAL_CHARGE';
    const WITHDRAWAL_COMMISSION = 'WITHDRAWAL_COMMISSION';
    const COMMISSION_CASH_PAYOUT = 'COMMISSION_CASH_PAYOUT';
    const COMMISSION_WALLET_PAYOUT = 'COMMISSION_WALLET_PAYOUT';
    const ADMIN_WALLET_REFILL = 'ADMIN_WALLET_REFILL';
    const BILL_PAYMENT = 'BILL_PAYMENT';
    const CASHBACK = 'CASHBACK';
    const BILL_PAYMENT_CHARGE ='BILL_PAYMENT_CHARGE';
    const MERCHANT_PAYMENT_CHARGE = 'MERCHANT_PAYMENT_CHARGE';
    const P2P_PAYMENT_CHARGE = 'P2P_PAYMENT_CHARGE';
    const WITHDRAWAL_CHARGE_REFUND = 'WITHDRAWAL_CHARGE_REFUND';
    const WITHDRAWAL_REFUND = 'WITHDRAWAL_REFUND';
    const WALLET_TRANSACTION_REFUND = 'WALLET_TRANSACTION_REFUND';


}
